import { Tomorrow } from "next/font/google";
import "./globals.css";
import MenuBar from "@/components/ui/MenuBar";
import PageTransition from "@/components/ui/PageTransition";
import StairEffect from "@/components/ui/StairEffect";

// Define the Tomorrow font
const tomorrowFont = Tomorrow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-tomorrowFont",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${tomorrowFont.variable} font-sans`}>
        <MenuBar />
        <StairEffect />
        <PageTransition>
          {/**Next.js is a file based application, using the child prop it will refer to the app
           * file dicrectory and since we have our menubar and navbar as wrapped components
           * Interacting with the navbar it direct us to the other folder's page i.e children */}
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
